# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-22 21:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verified', models.NullBooleanField()),
                ('offset', models.FloatField(blank=True, null=True)),
                ('duration', models.FloatField(blank=True, null=True)),
                ('filename', models.FilePathField(verbose_name='./collections')),
            ],
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.FilePathField(allow_files=False, allow_folders=True, path=b'd:/workspace/pika_project/collections/', recursive=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, default=None, max_digits=9, null=True)),
                ('datum', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('count_estimate', models.IntegerField(blank=True, default=None, null=True)),
                ('description', models.TextField(blank=True, default=None)),
                ('notes', models.TextField(blank=True, default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Observer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('institution', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('filename', models.FilePathField(match='\\.mp3$', path=b'd:/workspace/pika_project/collections/', recursive=True)),
                ('duration', models.FloatField(blank=True, default=None, null=True)),
                ('sample_frequency', models.FloatField(blank=True, default=None, null=True)),
                ('device', models.CharField(blank=True, default=None, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, default=None)),
                ('processed', models.NullBooleanField(default=None)),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pika_app.Collection')),
            ],
        ),
        migrations.AddField(
            model_name='collection',
            name='observer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pika_app.Observer'),
        ),
        migrations.AddField(
            model_name='call',
            name='recording',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pika_app.Recording'),
        ),
    ]
