# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pika_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='filename',
            field=models.FilePathField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='collection',
            name='folder',
            field=models.FilePathField(allow_files=False, allow_folders=True, path='d:/workspace/pika_project/collections/', recursive=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='filename',
            field=models.FilePathField(blank=True, default=None, match='\\.mp3$', path='d:/workspace/pika_project/collections/', recursive=True),
        ),
        migrations.AlterField(
            model_name='recording',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
