# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-08 06:26
from __future__ import unicode_literals

from django.db import migrations, models
import pika_app.models


class Migration(migrations.Migration):

    dependencies = [
        ('pika_app', '0003_auto_20171002_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recording',
            name='recording_file',
            field=models.FileField(default='', upload_to=pika_app.models.recording_path),
        ),
    ]
